version: '3'

services:
  crawler:
    build: .
    # command: /bin/bash -c "python main.py"
    volumes:
      - ./:/app
    environment:
      TZ: Asia/Tokyo
      # PYPPETEER_CHROMIUM_REVISION: 839847
